#!/bin/bash

- name: create ec2 and route53
  #hosta: all
  hosts: local
  connection: local
  vars:
    sg_id: "sg-0567d5e3a3afae3a2" 
    ami_id: "ami-0220d79f3f480ecf5"
    ZONE_ID: "Z0264884DOSR5KP2H7MK"
    domain_name: "ljnag.space"
    env: dev
    instances:
    - mongodb
    - catalogue
    - frontend
  tasks:
  - name: install python dependencies to connect with aws
    ansible.builtin.pip:
      name: "{{ item }}"
      state: present
    loop:
    - botocore
    - boto3  
  - name: Create EC2 instance 
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      image_id: "{{ ami_id }}"
      security_group: "{{ sg_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"  
    register: ec2_output

  - name: print output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"  
      
  - name: create route53
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address}}"
      wait: true    
    loop: "{{ ec2_output.results }}"

  - name: create route53
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{ domain_name }}" # roboshop-dev.ljnag.space for frontend
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address}}"
      wait: true    
    loop: "{{ ec2_output.results }}"
    when: item.item == frontend